#!/bin/bash

cd

TESTS_DIST_LOCATION="https://github.com/deib-polimi/modaclouds-tests.git"
TESTS_DIST_BRANCH="master"

touch ~/.bashrc_httpagent

sudo apt-get update -y
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
sudo apt-get install build-essential -y

sudo apt-get install default-jre default-jdk -q -y
export JAVA_HOME=/usr/lib/jvm/default-java
echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc_httpagent

source ~/.bashrc_httpagent

cd
wget https://www.dropbox.com/s/tg0pacw4zip6d6u/http-agent-helper-0.1.war

sudo apt-get install -y tomcat7
sudo cp ~/http-agent-helper-0.1.war /var/lib/tomcat7/webapps/
