#!/bin/bash

cd

TESTS_DIST_LOCATION="https://github.com/deib-polimi/modaclouds-tests.git"
TESTS_DIST_BRANCH="master"

touch ~/.bashrc_httpagent

sudo apt-get update -y
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
# sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
sudo apt-get install build-essential -y

sudo apt-get install maven git -y

export M2_HOME=/usr/share/maven
echo "export M2_HOME=/usr/share/maven" >> ~/.bashrc_httpagent
export M2=$M2_HOME/bin
echo "export M2=\$M2_HOME/bin" >> ~/.bashrc_httpagent
export PATH=$M2:$PATH
echo "export PATH=\$M2:\$PATH" >> ~/.bashrc_httpagent

sudo apt-get install default-jre default-jdk -q -y
export JAVA_HOME=/usr/lib/jvm/default-java
echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.bashrc_httpagent

cd
sudo rm -rf modaclouds-tests
git clone $TESTS_DIST_LOCATION -b $TESTS_DIST_BRANCH
cd modaclouds-tests/http-agent-helper
mvn clean package -DskipTests -U

sudo apt-get install -y tomcat7
cd target
sudo cp http-agent-helper-0.1.war /var/lib/tomcat7/webapps/
